// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fun_maxmin
arma::mat fun_maxmin(const arma::mat& X, const arma::mat& Y, const int n_subset, const int d);
RcppExport SEXP _odham_fun_maxmin(SEXP XSEXP, SEXP YSEXP, SEXP n_subsetSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_maxmin(X, Y, n_subset, d));
    return rcpp_result_gen;
END_RCPP
}
// fun_threshold
arma::vec fun_threshold(const arma::mat& X_clean, const arma::mat& Y_clean, const int d, const int B);
RcppExport SEXP _odham_fun_threshold(SEXP X_cleanSEXP, SEXP Y_cleanSEXP, SEXP dSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_clean(X_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_clean(Y_cleanSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_threshold(X_clean, Y_clean, d, B));
    return rcpp_result_gen;
END_RCPP
}
// fun_T_test
arma::vec fun_T_test(const arma::mat& X2, const arma::mat& Y2, const arma::mat& X_clean, const arma::mat& Y_clean, const arma::vec& TT, const int p, const int d);
RcppExport SEXP _odham_fun_T_test(SEXP X2SEXP, SEXP Y2SEXP, SEXP X_cleanSEXP, SEXP Y_cleanSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_clean(X_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_clean(Y_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_T_test(X2, Y2, X_clean, Y_clean, TT, p, d));
    return rcpp_result_gen;
END_RCPP
}
// fun_maxmin_new
arma::mat fun_maxmin_new(const arma::cube& Xbs, const arma::mat& Y, const int n_subset);
RcppExport SEXP _odham_fun_maxmin_new(SEXP XbsSEXP, SEXP YSEXP, SEXP n_subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbs(XbsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type n_subset(n_subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_maxmin_new(Xbs, Y, n_subset));
    return rcpp_result_gen;
END_RCPP
}
// fun_threshold_new
arma::vec fun_threshold_new(const arma::cube& Xbs_clean, const arma::mat& Y_clean, const int B);
RcppExport SEXP _odham_fun_threshold_new(SEXP Xbs_cleanSEXP, SEXP Y_cleanSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbs_clean(Xbs_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_clean(Y_cleanSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_threshold_new(Xbs_clean, Y_clean, B));
    return rcpp_result_gen;
END_RCPP
}
// fun_T_test_new
arma::vec fun_T_test_new(const arma::cube& X2bs, const arma::mat& Y2, const arma::cube& Xbs_clean, const arma::mat& Y_clean, const arma::vec& TT);
RcppExport SEXP _odham_fun_T_test_new(SEXP X2bsSEXP, SEXP Y2SEXP, SEXP Xbs_cleanSEXP, SEXP Y_cleanSEXP, SEXP TTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type X2bs(X2bsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y2(Y2SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Xbs_clean(Xbs_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_clean(Y_cleanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type TT(TTSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_T_test_new(X2bs, Y2, Xbs_clean, Y_clean, TT));
    return rcpp_result_gen;
END_RCPP
}
// test
NumericVector test(const arma::mat& X2, const arma::mat& X1);
RcppExport SEXP _odham_test(SEXP X2SEXP, SEXP X1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    rcpp_result_gen = Rcpp::wrap(test(X2, X1));
    return rcpp_result_gen;
END_RCPP
}
// sample_index
arma::uvec sample_index(const int& size, const arma::mat& Y);
RcppExport SEXP _odham_sample_index(SEXP sizeSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_index(size, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_odham_fun_maxmin", (DL_FUNC) &_odham_fun_maxmin, 4},
    {"_odham_fun_threshold", (DL_FUNC) &_odham_fun_threshold, 4},
    {"_odham_fun_T_test", (DL_FUNC) &_odham_fun_T_test, 7},
    {"_odham_fun_maxmin_new", (DL_FUNC) &_odham_fun_maxmin_new, 3},
    {"_odham_fun_threshold_new", (DL_FUNC) &_odham_fun_threshold_new, 3},
    {"_odham_fun_T_test_new", (DL_FUNC) &_odham_fun_T_test_new, 5},
    {"_odham_test", (DL_FUNC) &_odham_test, 2},
    {"_odham_sample_index", (DL_FUNC) &_odham_sample_index, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_odham(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
