# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fun_maxmin <- function(X, Y, n_subset, d) {
    .Call(`_odham_fun_maxmin`, X, Y, n_subset, d)
}

fun_threshold <- function(X_clean, Y_clean, d, B) {
    .Call(`_odham_fun_threshold`, X_clean, Y_clean, d, B)
}

fun_T_test <- function(X2, Y2, X_clean, Y_clean, TT, p, d) {
    .Call(`_odham_fun_T_test`, X2, Y2, X_clean, Y_clean, TT, p, d)
}

fun_maxmin_new <- function(Xbs, Y, n_subset) {
    .Call(`_odham_fun_maxmin_new`, Xbs, Y, n_subset)
}

fun_threshold_new <- function(Xbs_clean, Y_clean, B) {
    .Call(`_odham_fun_threshold_new`, Xbs_clean, Y_clean, B)
}

fun_T_test_new <- function(X2bs, Y2, Xbs_clean, Y_clean, TT) {
    .Call(`_odham_fun_T_test_new`, X2bs, Y2, Xbs_clean, Y_clean, TT)
}

test <- function(X2, X1) {
    .Call(`_odham_test`, X2, X1)
}

sample_index <- function(size, Y) {
    .Call(`_odham_sample_index`, size, Y)
}

